### PR TITLE
Added url as 3rd param

### LINKED ISSUE #6: Wrong Base URL for Premium usage
When using the Premium Data plan the Base URL should be `https://secure.geonames.net` instead of `https://secure.geonames.org`.

This information came from the email when purchasing a Premium plan

`We have enabled your account and you can access the premium server with the domain ws.geonames.net and the ssl domain is https://secure.geonames.net (.net instead of .org for the free server)`

This seems to be the case for me as well since I seem to have hit the credits cap on the .org domain while .net works.

There's currently no way to properly override this. I suggest that we either have an additional parameter in the constructor, or move the base url to a config variable.

### PR DESCRIPTION
**Pull request by georgfranz**
If you have a commercial service, you can buy a custom subdomain. The url isn't changable from outside, so I have added a 3rd param.

### CODE REVIEW

**Comment by Aternus** [comment]
Hey @georgfranz and welcome to the GeoNames Client!
I suggest making the 3rd parameter an associative array so we can add various config options without breaking the interface or introducing many setter/getter functions.
wdyt?

**Comment by Aternus** [comment]
Here are the specs from GeoNames:

Yes the domain should be configurable, also the free api support various
domain names (example. [secure.geonames.org](http://secure.geonames.org/) or [api.geonames.org](http://api.geonames.org/))

Premium users have additionally the possibility to add a parameter
'token' to all requests. This is a security feature to make sure nobody
else is using the username (such as former employees...)

Best-Availability users have a failover url they could use if the
primary end point for a reason is not reachable.  Optimally the client
library supports this and if some calls in a row end in a timeout it
switches for some hours to the failover server. However, this might be
too complicate for you to implement, just keep the possibility in mind
that the users of your library may want to change the endpoint
programmatically without having to restart their application.

**Comment by georgfranz** [comment]
> Hey @georgfranz and welcome to the GeoNames Client! I suggest making the 3rd parameter an associative array so we can add various config options without breaking the interface or introducing many setter/getter functions. wdyt?

Hi @Aternus - thanks for your fast reply :-)

Well, what other options do you have in mind? Like langunage / sorting / bias etc.?

Currently I can set all other options from outside - only the url wasn't possbile.

Best,
Georg

**Comment by Aternus** [comment]
@georgfranz here's the spec I was thinking about:

1. Ability to specify `apiUrl`
2. Ability to specify `fallbackApiUrl`
3. Ability to specify `connectionTimeout` (will deprecate the need for the [set/get of the timeout](https://github.com/Aternus/geonames-client/blob/master/src/Client.php#L383))
4. Ability to specify `fallbackUrlTrigger`. If calls with `apiUrl` reach `connectionTimeout` for `fallbackUrlTrigger` count, use `fallbackApiUrl` for the next call, then reset to `apiUrl` and reset the trigger count.

**Comment by rosspointon** [comment]
Hello - is this likely to get merged? We're having TLS trouble with secure.geonames & want to use api.geonames instead

**Comment by Aternus** [comment]
> Hello - is this likely to get merged? We're having TLS trouble with secure.geonames & want to use api.geonames instead

For us to merge the PR, please kindly ensure:
1. The tests for this PR are passing.
2. The Spec is implemented. Doesn't have to be everything at once, starting with the associative array having the URL is a good start.

**Comment by Aternus** [comment]
Resolved in #12

**Pull request closed without merging**
